---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-deployment
  template:
    metadata:
      labels:
        app: node-deployment
    spec:
      containers:
        - name: node-deployment
          image: hieuphamdn93/nodetest:$COMMIT_SHA1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app: node-deployment
  ports:
    - port: 3000
      targetPort: 3000
